exports.seed = function (knex) {
  return knex('activities')
    .del()
    .then(function () {
      return knex('activities').insert([
        {
          id: 1,
          title: 'Yoga',
          category: 'Health',
          info: 'A gentle Vinyāsa flow to start the day. Suitable for all levels.',
          date: 'Every Thursday at ',
          time: '10am',
          location: 'Blue Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/YOG.jpg',
          ran_by: 'Kaia',
        },
        {
          id: 2,
          title: 'Movie Night',
          category: 'Fun',
          info: 'Are you a film lover? Come along and join our movie nights!',
          date: 'Every Friday at ',
          time: '7pm',
          location: 'Green Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/MOV.jpeg',
          ran_by: 'Finn',
        },
        {
          id: 3,
          title: 'Te Reo Classes',
          category: 'Culture',
          info: 'Come along and learn Te Reo Māori followed by kai and waita.',
          date: 'Every Monday at ',
          time: '5pm',
          location: 'Pink Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/te-reo2.jpeg',
          ran_by: 'Isaiah',
        },
        {
          id: 4,
          title: 'Cooking Classes',
          category: 'Cuisine',
          info: 'Learn some quick, easy, tasty recipes from a variety of cultures.',
          date: 'Every Wednesday at ',
          time: '5pm',
          location: 'Blue Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/COO.webp',
          ran_by: 'Courtney',
        },
        {
          id: 5,
          title: 'Poetry Reading',
          category: 'Fun',
          info: 'Why not try poetry? Weekly readings of poetry chosen in advance.',
          date: 'Sunday at ',
          time: '11am',
          location: 'Blue Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/poetry_image.jpeg',
          ran_by: 'Courtney',
        },
        {
          id: 6,
          title: 'Puppy Day',
          category: 'Fun',
          info: 'Puppy day! An all day play session with some lovable furry friends.',
          date: 'Saturday March 12 at ',
          time: '11am',
          location: 'Pink Room',
          recurring: false,
          frequency: '',
          image: './images/PUP.jpeg',
          ran_by: 'Dellon',
        },
        {
          id: 7,
          title: 'Book Club',
          category: 'Fun',
          info: 'Calling all book lovers! We read all genres, and love to talk all things books.',
          date: 'Every Tuesday at ',
          time: '5pm',
          location: 'Green Room',
          recurring: true,
          frequency: 'weekly',
          image: './images/BOO.png',
          ran_by: 'Cujo',
        },
      ])
    })
}
