exports.seed = async function(knex) {
  await knex('counsellors').del()
  await knex('counsellors').insert([
    {id: 1, name: 'Courtney Brown', pronouns: 'She/Her', speciality: 'LGBTQI+', photo: './images/COU.jpg', hours: 'Monday to Friday, Office Hours', biography: `Courtney offers a ‘pluralistic’ approach, working in partnership with clients as the experts in their own lives. Courtney has particular experience with self-compassion and mindfulness practices and has strong interests in neuropsychology and attachment theory. She has previously worked in hospital, palliative care, community and university settings.`},
    {id: 2, name: 'Christine Stewart', pronouns: 'They/Them', speciality: 'Job Support', photo: './images/CHR.jpg', hours: 'Monday to Friday, Office Hours', biography: `Christine has been a job support counsellor for many years now, and is always ready to help you find a job if you are struggling. They walk you through the process to be work-ready, and connect you with employers. There are also various training and development opportunities that you can access when you sign up for a session with them.`},
    {id: 3, name: 'Cujo Burton', pronouns: 'They/Them', speciality: 'Trauma & Grief', photo: './images/CUJ.jpg', hours: 'Monday to Friday, Office Hours', biography: `Cujo works with people in a non-judgemental, person-centred way exploring their responses to life issues. They work "existentially" placing peoples' values, beliefs, and resourcefulness at the centre of the work. Drawing from counselling methods like art therapy, psychodrama, cognitive behavioural therapy, Te Wheke and focusing their approach is tailored to suit needs.`},
    {id: 4, name: 'Dellon Thomas', pronouns: 'She/Her', speciality: 'Anxiety & Stress', photo: './images/DEL.jpg', hours: 'Monday to Friday, Office Hours', biography: `Dellon is an experienced counsellor, group worker and supervisor who has been in private practice since 1987. She is committed to bringing spontaneity and creativity to all aspects of life and work. Dellon has worked extensively with clients with migrant and refugee backgrounds. Dellon also specialises in group work and regularly runs groups for strengthening resilience.`},
    {id: 5, name: 'Natalie Sherwood', pronouns: 'He/Him', speciality: 'Te Whare Tapa Whā', photo: './images/NAT.jpg', hours: 'Monday to Friday, Office Hours', biography: `Natalie has a unique set of counselling skills, developed over 25 years, combining narrative therapy, cognitive behaviour therapy, mindfulness meditation, emotional agility and appreciative inquiry. Natalie also combines this with the practice of the latest research into happiness, trauma recovery, resilience, and positive psychology.`},
    {id: 6, name: 'Pauline Gertrude', pronouns: 'They/Them', speciality: 'Relationships', photo: './images/PAU.jpg', hours: 'Monday to Friday, Office Hours', biography: `Providing counselling services for individuals and couples Pauline's therapy is a non-judgemental way to assess your situation, see past limiting patterns and constructively move toward a desired outcome. A range of approaches are available, including emotionally focussed therapy, cognitive behavioural therapy,  psychodrama and a research-based model for couples.`},
    {id: 7, name: 'Peter Plum', pronouns: 'He/Him', speciality: 'Addiction', photo: './images/PET.jpg', hours: 'Monday to Friday, Office Hours', biography: `Peter works with a variety of approaches to offer clients different options and ways to process through their difficulties. He enjoys making the counselling process as creative as possible by offering clients the use of drawing or working with objects or cards. He has been in the practice for over 5 years now, and has helped many people overcome addiction.`},
    {id: 8, name: 'Tyrone Baxter', pronouns: 'They/Them', speciality: 'Anxiety & Stress', photo: './images/TYR.jpg', hours: 'Monday to Friday, Office Hours', biography: `Tyrone specialises in working with Māori whanau, including rangatahi and tamariki. She has particular skills and knowledge related to working with those affected by violence and abuse and those struggling with their cultural identity. She is also works with people presenting with a range of mental health issues, including depression, anxiety and stress.`},
    {id: 9, name: 'Penelope Smith', pronouns: 'They/Them', speciality: 'LGBTQI+', photo: './images/PEN.jpg', hours: 'Monday to Friday, Office Hours', biography: `Penelope believes that an open, non-judgemental environment is vital to fostering a safe space for people to share about experiences. They specialise in dealing with those struggling with their cultural identity, and has been in the practice for many years helping clients manage a range of mental health issues, especially in the area of identity.`},
    {id: 10, name: 'Jasmine Jones', pronouns: 'She/Her', speciality: 'Relationships', photo: './images/JAS.jpg', hours: 'Monday to Friday, Office Hours', biography: `Jasmine specialises in psychotherapy. She has helped couples of all types to explore, recognize, and resolve conflicts in an effort to improve their relationships and interactions. She is also an active speaker in many relationship workshops, and has published various books and resources in the area of dealing with relationship issues.`},
    {id: 11, name: 'Peter Parker', pronouns: 'He/Him', speciality: 'Trauma & Grief', photo: './images/PEP.jpg', hours: 'Monday to Friday, Office Hours', biography: `Peter has worked in the military as a PTSD specialist. He brings with him a rich background in supporting people experiencing trauma, especially in an intense environment. He has been recognised for his studies on how to equip families of individuals suffering from trauma and grief. Peter has been recognised as an expert in this field.`},
    {id: 12, name: 'Bruce Wayne', pronouns: 'He/Him', speciality: 'Anxiety & Stress', photo: './images/BRW.jpg', hours: 'Monday to Friday, Office Hours', biography: `Bruce provides a specialised programme called 'Stress Buster,' in helping individuals come out victorious in their journey with anxiety and stress. He has been actively facilitating workshops and programmes in this area for many years now, and has been recognised by the Psychological Associations in different countries around the world.`},
    {id: 13, name: 'Juan Dela Cruz', pronouns: 'He/Him', speciality: 'Job Support', photo: './images/JDC.jpg', hours: 'Monday to Friday, Office Hours', biography: `Juan specialises in providing assistance for people struggling to find a job. He provides an individualistic approach to helping individuals discover their strengths and potentials, and use it to their advantage. Juan will help you gain confidence in going through the process of job application, and make sure you will be sucessful.`},
    {id: 14, name: 'Maybel Zeng', pronouns: 'They/Them', speciality: 'Addiction', photo: './images/MAZ.jpg', hours: 'Monday to Friday, Office Hours', biography: `Maybel has done years of research in the area of addiction, and how the principle of replacement could be help a person come up with strategies in battling this issue. Maybel is very hands-on in doing a thorough diagnosis and therapy plan for clients. He also facilitates group therapy which has been found effective in treating these kind of issues.`},
    {id: 15, name: 'Amara Keita', pronouns: 'She/Her', speciality: 'Trauma & Grief', photo: './images/AMK.jpg', hours: 'Monday to Friday, Office Hours', biography: `Amara has developed a coping strategy programme in dealing with grief and traumatic experiences. She believes in the power of self-discovery, which is part of the programme that she offers. She mployes a very person-centred and flexible approach in coming up with customised therapy programme, to suit the needs of the client.`},
  ]);
};
