exports.seed = async function (knex) {
  await knex('free-items').del()
  await knex('free-items').insert([
    {
      id: 1,
      name: 'James',
      donorRoom: '12',
      item: '100 pc Puzzle',
      description: 'A 100 Piece Jigsaw Puzzle showing a castle picture',
      quantity: '1',
      category: 'Toys & Games',
      donateDate: '2022-02-20',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 2,
      name: 'Mark',
      donorRoom: '11',
      item: 'Dart Board',
      description: 'Used but in good condition board for anyone who would like it.',
      quantity: '1',
      category: 'Sports & Outdoors',
      donateDate: '2022-02-19',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 3,
      name: 'Linda',
      donorRoom: '21',
      item: 'Harley Davidson T-Shirt',
      description: 'Free size shirt',
      quantity: '2',
      category: 'Clothing & Apparel',
      donateDate: '2022-02-23',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 4,
      name: 'Kerry',
      donorRoom: '14',
      item: 'TRESemmé Shampoo 350ML',
      description: 'new and unused bottle of shampoo',
      quantity: '20',
      category: 'Health & Beauty',
      donateDate: '2022-02-25',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 5,
      name: 'Abby',
      donorRoom: '15',
      item: 'Protective face masks',
      description: '1 box of face masks',
      quantity: '50',
      category: 'Health & Beauty',
      donateDate: '2022-02-22',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 6,
      name: 'Angelique',
      donorRoom: '16',
      item: 'Atomic Habits',
      description: 'really good read, free to anyone who wants it!',
      quantity: '1',
      category: 'Books, Music & Movies',
      donateDate: '2022-02-12',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 7,
      name: 'Emma',
      donorRoom: '17',
      item: 'Free Garden Pots!!',
      description: 'got 2 used pots that I don\'t need anymore.',
      quantity: '2',
      category: 'DIY, Garden & Pet',
      donateDate: '2022-02-24',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 8,
      name: 'Rebecca',
      donorRoom: '22',
      item: 'L.A.B. record',
      description: 'L.A.B. 2017 Album',
      quantity: '1',
      category: 'Books, Music & Movies',
      donateDate: '2022-02-24',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
    {
      id: 9,
      name: 'Ceri',
      donorRoom: '23',
      item: 'USB-C Cable',
      description: 'unused and giving away as I already have one that I\'m using',
      quantity: '1',
      category: 'Electronics & Computer',
      donateDate: '2022-02-25',
      status: 'Available',
      claimedBy: '',
      claimerRoom: '',
    },
  ])
}
